### ISSUE TITLE
How to set up a redirect on authentication?

### ISSUE THREAD

**Issue by 10000multiplier** [codingki/react-native-expo-template#11]
```expo://10.0.0.79:19000```is my site_url in app.supabase.io settings.

After clicking the magic link I am redirected back to the app but then the app stays on the login screen 🤔.

**Comment by codingki** [comment]
Yeah I think after you verify your email, you still need to login again

**Comment by 10000multiplier** [comment]
> Yeah I think after you verify your email, you still need to login again

It seems to be an issue with supabase

https://github.com/supabase/gotrue/issues/140
