### ISSUE TITLE
ThemeProvider Rapid UI error on expo start

### ISSUE THREAD

**Issue by adnaneghalem** [codingki/react-native-expo-template#12]
This is the error I am getting : 
node_modules/react-native-rapi-ui/provider/ThemeProvider.tsx: Property body[12] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"

Thanks for your help

**Comment by codingki** [comment]
can you give me more details, what template are you using? btw check this https://stackoverflow.com/questions/68659516/react-native-property-body41-of-blockstatement-expected-node-to-be-of-a-type

**Comment by codingki** [comment]
@adnaneghalem
