### ISSUE TITLE
Supabase template throws when running on iOS

### ISSUE THREAD

**Issue by cwlsn** [codingki/react-native-expo-template#15]
Have found an odd error, but am new to React Native and Expo, so wondering if there's a known solution/workaround I can't find.

When running the iOS simulator (iPhone 12), I get this error which leads to the app not running:

```
TypeError: undefined is not an object (evaluating 'window.location.href')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```

It works in browser, and if I open the remote JS debugging in the iOS simulator, it does work. Seems like the debugger runs the code in that browser when it's open, making `window.location` defined. Is there a fix besides leaving the debugger open?

**Comment by codingki** [comment]
I'm sorry, currently I can't fix it because I don't have the environment to reproduce this error. Feel free to contribute ❤️

**Comment by cwlsn** [comment]
If I figure it out I'll PR!

**Comment by codingki** [comment]
Thanks for your contribution Connor!
