### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'auth.user')

### ISSUE THREAD

**Issue by Tshibek** [codingki/react-native-expo-template#2]
Error in AppNavigator.js with useContext:
Undefined is not an object(evaluating "auth.user")

**Comment by codingki** [comment]
which template did u use @Tshibek ?
did you already fill your firebase config? 
if not try fill this firebase config to your config inside " ./navigation/index.tsx"
`const firebaseConfig = {
	apiKey: '',
	authDomain: '',
	databaseURL: '',
	projectId: '',
	storageBucket: '',
	messagingSenderId: '',
	appId: '',
};`

**Comment by Tshibek** [comment]
I used template-javascript-bottom-tabs-with-auth-flow and i added my config like in readme was so you tell me to use typescript then javascript

**Comment by codingki** [comment]
if you using the typescript one, its inside the **./navigation/index.tsx** file. but if you using the javascript one its inside **./navigation/AppNavigator.js**

**Comment by Tshibek** [comment]
But I did it everything good, because if i  do something like that in ./navigation/AppNavigator.js

`export default () => {
	const user = AuthContext.user;
	return (
		<NavigationContainer>
			{user == null && <Loading />}
			{user == false && <Auth />}
			{user == true && <Main />}
		</NavigationContainer>
	);
};`
its without erro what i said up, added to database my user, but its loading all the time because it not see user type

**Comment by codingki** [comment]
`const auth = useContext(AuthContext);
const user = auth.user;`
try do it like this

**Comment by Tshibek** [comment]
If I used it i have error like above
