### ISSUE TITLE
Sign up error

### ISSUE THREAD

**Issue by thareekanvar** [codingki/react-native-expo-template#20]
![image](https://user-images.githubusercontent.com/26960181/175293394-ea2780a0-ec1e-4972-b908-626048b146e0.png)

https://github.com/codingki/react-native-expo-template/tree/master/template-typescript-bottom-tabs-supabase-auth-flow

**Comment by thareekanvar** [comment]
@cwlsn @codingki

**Comment by codingki** [comment]
@thareekanvar have you change `"supabaseUrl"` and `"supabaseKey"` to your credentials? https://github.com/codingki/react-native-expo-template/blob/75e6d901c0b5e0239ec5503c407d8cfd9e3e31bb/template-typescript-bottom-tabs-supabase-auth-flow/src/initSupabase.ts#L5

**Comment by thareekanvar** [comment]
> @thareekanvar have you change `"supabaseUrl"` and `"supabaseKey"` to your credentials?
> 
> https://github.com/codingki/react-native-expo-template/blob/75e6d901c0b5e0239ec5503c407d8cfd9e3e31bb/template-typescript-bottom-tabs-supabase-auth-flow/src/initSupabase.ts#L5

yes changed

**Comment by codingki** [comment]
@thareekanvar Could you give me an ss of your `initSupabase.ts`? because it is indicating an error on your vscode

**Comment by thareekanvar** [comment]
![image](https://user-images.githubusercontent.com/26960181/175294814-47e84a3b-ce09-489e-8b60-814072db312e.png)

**Comment by thareekanvar** [comment]
@codingki ss ...

**Comment by codingki** [comment]
You can delete that @thareekanvar there's your credentials

**Comment by codingki** [comment]
@thareekanvar 
Try : 
1. Stop your server
2. Delete your `node_modules`
3. `npm install` again

**Comment by thareekanvar** [comment]
i used yarn install.. is that a problem..??

> @thareekanvar Try :
> 
> 1. Stop your server
> 2. Delete your `node_modules`
> 3. `npm install` again

**Comment by thareekanvar** [comment]
> @thareekanvar not a problem

same error
