### ISSUE TITLE
Fetching data

### ISSUE THREAD

**Issue by Pelema** [codingki/react-native-expo-template#21]
Hi I'm trying to fetch data from supabase via react expo but I'm not getting any data back do you perhaps know what the issue is or can you guide me maybe I'm misunderstanding some concepts. The same code works on reactJS

**Comment by etherealsunshine** [comment]
can you share your code?

**Comment by Pelema** [comment]
Hi sorry I actually found the solution, mistyped something. Thank you for your response.
