### ISSUE TITLE
firebase import error

### ISSUE THREAD

**Issue by tuld01061** [codingki/react-native-expo-template#9]
> Attempted import error: 'app' is not exported from 'firebase/app' (imported as 'firebase')

This error happen with firebase version 8.
Fixed it by changing:
`import * as firebase from "firebase";`
into
`import firebase from "firebase";`

Preference: https://firebase.google.com/support/release-notes/js#version_800_-_october_26_2020

**Comment by codingki** [comment]
@tuld01061 good catch!, thanks for the info

**Comment by codingki** [comment]
solved in #10
